#
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Device configuration for the docomo GALAXY S III (SC-06D), codename d2dcm.
#

LOCAL_PATH := device/samsung/d2dcm

# Everything shared with the rest of the MSM8960 d2 family: audio, camera,
# display, GPS, Bluetooth, Wi-Fi, power HAL, media codecs. d2att-unified
# already folds in d2-common and msm8960-common.
$(call inherit-product, device/samsung/d2att/device.mk)

# docomo-specific blobs (RIL, emoji, FeliCa). Generated by extract-files.sh.
$(call inherit-product-if-exists, vendor/samsung/d2dcm/d2dcm-vendor.mk)

# Overlays -------------------------------------------------------------------
# Prepend so that d2dcm resources win over the d2att ones inherited above.
DEVICE_PACKAGE_OVERLAYS := \
    device/samsung/d2dcm/overlay \
    $(DEVICE_PACKAGE_OVERLAYS)

# Properties -----------------------------------------------------------------
# d2att pulls in its own system_prop.mk via its device.mk. Appending here means
# the d2dcm values are written after the d2att ones, so ours take effect.
PRODUCT_PROPERTY_OVERRIDES += \
    rild.libargs=-d\ /dev/smd0 \
    telephony.lteOnGsmDevice=1 \
    ro.telephony.default_network=9 \
    ro.ril.enable.dcm.feature=1 \
    ro.config.libemoji=libemoji_docomo.so \
    ro.hw.oneseg=nmi326

# Ramdisk --------------------------------------------------------------------
PRODUCT_PACKAGES += \
    init.oneseg.rc

# ISDB-T / 1seg --------------------------------------------------------------
# The kernel driver (drivers/media/nmi326) is enabled by
# lineageos_d2dcm_defconfig, so /dev/isdbt appears without anything here.
#
# What is NOT here, and what has to be added once the stock stack has been
# analysed with tools/oneseg-probe.sh:
#
#   - the closed-source tuner/demod .so files
#   - the NMI326 firmware blob
#   - the 1seg application and its framework glue, if the stock app is used
#
# No decryption keys are needed: 1seg is broadcast unscrambled.
#
# Add them to proprietary-files.txt rather than listing them here, so that
# extract-files.sh can pull them off a real device.
#
# See docs/05-ワンセグ移植の手順.md.
